services:
  - type: web
    name: techvilocrm
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: PYTHON_VERSION
        value: 3.12.0
